<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KJ400B0" failures="1" tests="5" name="EmployeeServiceTest" time="0.008" errors="0" timestamp="2022-11-06T20:32:09 IST">
  <testcase classname="com.service.EmployeeServiceTest" name="removeEmployeeTest" time="0.003"/>
  <testcase classname="com.service.EmployeeServiceTest" name="getAllEmployeeTest" time="0.002"/>
  <testcase classname="com.service.EmployeeServiceTest" name="getEmployeeTest" time="0.003"/>
  <testcase classname="com.service.EmployeeServiceTest" name="searchEmployeeTest" time="0.003"/>
  <testcase classname="com.service.EmployeeServiceTest" name="updateSalaryTest" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [48600.0] but found [48000.0]">
      <![CDATA[java.lang.AssertionError: expected [48600.0] but found [48000.0]
at com.service.EmployeeServiceTest.updateSalaryTest(EmployeeServiceTest.java:70)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- updateSalaryTest -->
</testsuite> <!-- EmployeeServiceTest -->
